config/routes.rb
Rails.application.routes.draw do
  resources :trial_models

end

app/models/trial_model.rb
class TrialModel < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trial_models_controller.rb
class TrialModelsController < ApplicationController
  before_action :set_trial_model, only: [:show, :edit, :update, :destroy]

  # GET /trial_models
  # GET /trial_models.json
  def index
    @trial_models = TrialModel.all
  end

  # GET /trial_models/1
  # GET /trial_models/1.json
  def show
  end

  # GET /trial_models/new
  def new
    @trial_model = TrialModel.new
  end

  # GET /trial_models/1/edit
  def edit
  end

  # POST /trial_models
  # POST /trial_models.json
  def create
    @trial_model = TrialModel.new(trial_model_params)

    respond_to do |format|
      if @trial_model.save
        format.html { redirect_to @trial_model, notice: 'Trial model was successfully created.' }
        format.json { render :show, status: :created, location: @trial_model }
      else
        format.html { render :new }
        format.json { render json: @trial_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trial_models/1
  # PATCH/PUT /trial_models/1.json
  def update
    respond_to do |format|
      if @trial_model.update(trial_model_params)
        format.html { redirect_to @trial_model, notice: 'Trial model was successfully updated.' }
        format.json { render :show, status: :ok, location: @trial_model }
      else
        format.html { render :edit }
        format.json { render json: @trial_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trial_models/1
  # DELETE /trial_models/1.json
  def destroy
    @trial_model.destroy
    respond_to do |format|
      format.html { redirect_to trial_models_url, notice: 'Trial model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trial_model
      @trial_model = TrialModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trial_model_params
      params.require(:trial_model).permit(:trial_attribute)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trial_models_helper.rb
module TrialModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinefoldTrial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trial_models/_form.html.erb
<%= form_for(@trial_model) do |f| %>
  <% if @trial_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trial_model.errors.count, "error") %> prohibited this trial_model from being saved:</h2>

      <ul>
      <% @trial_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trial_attribute %><br>
    <%= f.text_field :trial_attribute %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trial_models/edit.html.erb
<h1>Editing trial_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @trial_model %> |
<%= link_to 'Back', trial_models_path %>

app/views/trial_models/index.html.erb
<h1>Listing trial_models</h1>

<table>
  <thead>
    <tr>
      <th>Trial attribute</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trial_models.each do |trial_model| %>
      <tr>
        <td><%= trial_model.trial_attribute %></td>
        <td><%= link_to 'Show', trial_model %></td>
        <td><%= link_to 'Edit', edit_trial_model_path(trial_model) %></td>
        <td><%= link_to 'Destroy', trial_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trial model', new_trial_model_path %>

app/views/trial_models/new.html.erb
<h1>New trial_model</h1>

<%= render 'form' %>

<%= link_to 'Back', trial_models_path %>

app/views/trial_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trial attribute:</strong>
  <%= @trial_model.trial_attribute %>
</p>

<%= link_to 'Edit', edit_trial_model_path(@trial_model) %> |
<%= link_to 'Back', trial_models_path %>